apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config-env
  namespace: default
data:
  AUTH_MONGO_URL: mongodb://auth-mongo-srv/auth
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-config-secret
  namespace: default
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  JWT_KEY: YmFyCg==
