apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: huyhoang1001/payments
          env:
            # Define the environment variable
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: payments-config-env
                  key: NATS_URL
            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: payments-config-env
                  key: NATS_CLUSTER_ID
            - name: PAYMENTS_MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: payments-config-env
                  key: PAYMENTS_MONGO_URL
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: payments-config-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
