apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config-env
  namespace: default
data:
  PAYMENTS_MONGO_URL: mongodb://payments-mongo-srv/payments-db
  NATS_URL: http://nats-srv:4222
  NATS_CLUSTER_ID: bookstore
---
apiVersion: v1
kind: Secret
metadata:
  name: payments-config-secret
  namespace: default
type: Opaque
data:
  JWT_KEY: YmFyCg==
  STRIPE_KEY: sk_test_51LtUCpLpNaCMRQGT0uj409rvMbxBCNdwxIjeAfo3kLd1YX9BYhPmOaxhhKSCVQytMKOhofQH5aBFvAskd3PMu5SI00wvtadaG3

