name: tests-auth

on:
  push:
    branches: [ main ]
    paths:
      - 'auth/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'auth/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Auth-Service:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Service-build
        run: cd auth && npm install

      - name: Eslint && Unit testing
        run: cd auth && npm run eslint && npm run test:ci

      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
