name: tests-books-service

on:
  push:
    branches: [ main ]
    paths:
      - 'books/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'books/**'

  workflow_dispatch:

jobs:
  Books-Service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Unit Testing
        run: cd books && npm install && npm run test:ci
