name: tests-orders-service

on:
  push:
    branches: [ main ]
    paths:
      - 'orders/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'orders/**'

  workflow_dispatch:

jobs:
  Orders-Service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Unit Testing
        run: cd orders && npm install && npm run test:ci
